# Generated by Django 4.2.11 on 2024-03-31 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(help_text='Percentage value (0 to 100)', validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
